<?php

use Illuminate\Database\Seeder;

class LocalidadesCDMXSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //

       DB::table('cat_localidad')->insert([
       	
['idMunicipio'=>272, 'nombre' => 'AZCAPOTZALCO'],
['idMunicipio'=>273, 'nombre' => 'COYOACAN'],
['idMunicipio'=>274, 'nombre' => 'CUAJIMALPA DE MORELOS'],
['idMunicipio'=>274, 'nombre' => 'CRUZ BLANCA'],
['idMunicipio'=>274, 'nombre' => 'SAN LORENZO ACOPILCO'],
['idMunicipio'=>274, 'nombre' => 'LA VENTA'],
['idMunicipio'=>274, 'nombre' => 'PUERTO LAS CRUCES (MONTE LAS CRUCES)'],
['idMunicipio'=>274, 'nombre' => 'TEOPAZULCO'],
['idMunicipio'=>274, 'nombre' => 'VALLE DE LAS MONJAS'],
['idMunicipio'=>274, 'nombre' => 'PROLONGACION CONSTITUCION'],
['idMunicipio'=>274, 'nombre' => 'PARAJE RIO BORRACHO'],
['idMunicipio'=>274, 'nombre' => 'EL ZARCO'],
['idMunicipio'=>274, 'nombre' => 'LA BOLSA (EL ENCINAL)'],
['idMunicipio'=>274, 'nombre' => 'LOS CAMPESINOS [RANCHO]'],
['idMunicipio'=>274, 'nombre' => 'SANTA ROSA'],
['idMunicipio'=>274, 'nombre' => 'PARAJE CERRO DE LOS PADRES'],
['idMunicipio'=>274, 'nombre' => 'SANTA LAURA [RANCHO]'],
['idMunicipio'=>274, 'nombre' => 'LA PAPA [ESCUELA NIÑOS HEROES]'],
['idMunicipio'=>274, 'nombre' => 'CONVENTO DEL DESIERTO DE LOS LEONES'],
['idMunicipio'=>274, 'nombre' => 'LA TROJE'],
['idMunicipio'=>274, 'nombre' => 'PUNTA GALICIA'],
['idMunicipio'=>274, 'nombre' => 'COLA DE PATO'],
['idMunicipio'=>274, 'nombre' => 'SANTIAGO YACUITLALPAN'],
['idMunicipio'=>274, 'nombre' => 'PUNTA AHUATENCO'],
['idMunicipio'=>274, 'nombre' => 'LOS LAURELES [RANCHO]'],
['idMunicipio'=>275, 'nombre' => 'GUSTAVO A. MADERO'],
['idMunicipio'=>276, 'nombre' => 'IZTACALCO'],
['idMunicipio'=>277, 'nombre' => 'IZTAPALAPA'],
['idMunicipio'=>278, 'nombre' => 'LA MAGDALENA CONTRERAS'],
['idMunicipio'=>278, 'nombre' => 'MANANTIALES DE MONTE ALEGRE'],
['idMunicipio'=>278, 'nombre' => 'LAS LLANTAS'],
['idMunicipio'=>278, 'nombre' => 'SEGUNDO DINAMO'],
['idMunicipio'=>278, 'nombre' => 'LAS GOLONDRINAS'],
['idMunicipio'=>278, 'nombre' => 'VIVERO POTRERITOS'],
['idMunicipio'=>278, 'nombre' => 'PRIMER DINAMO'],
['idMunicipio'=>278, 'nombre' => 'EL GAVILLERO'],
['idMunicipio'=>278, 'nombre' => 'CAMINO DE SAYULA'],
['idMunicipio'=>278, 'nombre' => 'COAPANOAYA'],
['idMunicipio'=>278, 'nombre' => 'TOTOLAPA'],
['idMunicipio'=>278, 'nombre' => 'SEHUAYA'],
['idMunicipio'=>278, 'nombre' => 'TERCER DINAMO'],
['idMunicipio'=>278, 'nombre' => 'CUARTO DINAMO'],
['idMunicipio'=>278, 'nombre' => 'LA BODEGA'],
['idMunicipio'=>278, 'nombre' => 'LA CAMPANA [RANCHO]'],
['idMunicipio'=>278, 'nombre' => 'LA ESCONDIDA'],
['idMunicipio'=>278, 'nombre' => 'LA POLEA'],
['idMunicipio'=>278, 'nombre' => 'CERRO PANZA [CAMPAMENTO FORESTAL]'],
['idMunicipio'=>278, 'nombre' => 'VALLE DEL TEZONTLE'],
['idMunicipio'=>278, 'nombre' => 'ALBERGUE ALPINO AJUSCO'],
['idMunicipio'=>278, 'nombre' => 'LOS CEDROS'],
['idMunicipio'=>278, 'nombre' => 'PARAJE EL RANCHO'],
['idMunicipio'=>278, 'nombre' => 'LOS TEJOCOTES'],
['idMunicipio'=>278, 'nombre' => 'PARAJE AYLA'],
['idMunicipio'=>278, 'nombre' => 'RANCHO VIEJO'],
['idMunicipio'=>278, 'nombre' => 'LA LOMA'],
['idMunicipio'=>278, 'nombre' => 'PROLONGACION ERMITAÑO'],
['idMunicipio'=>278, 'nombre' => 'GRANJA SOTO'],
['idMunicipio'=>278, 'nombre' => 'RINCON ESLAVA'],
['idMunicipio'=>278, 'nombre' => 'LA CAÑADA [PARQUE]'],
['idMunicipio'=>278, 'nombre' => 'PARAJE CHEPECANO'],
['idMunicipio'=>278, 'nombre' => 'RANCHO CHICHICASPA'],
['idMunicipio'=>278, 'nombre' => 'PARAJE CHICHICASPA'],
['idMunicipio'=>279, 'nombre' => 'VILLA MILPA ALTA'],
['idMunicipio'=>279, 'nombre' => 'SAN ANTONIO TECOMITL'],
['idMunicipio'=>279, 'nombre' => 'SAN BARTOLOME XICOMULCO'],
['idMunicipio'=>279, 'nombre' => 'SAN FRANCISCO TECOXPA'],
['idMunicipio'=>279, 'nombre' => 'SAN PABLO OZTOTEPEC'],
['idMunicipio'=>279, 'nombre' => 'SAN PEDRO ATOCPAN'],
['idMunicipio'=>279, 'nombre' => 'SAN SALVADOR CUAUHTENCO'],
['idMunicipio'=>279, 'nombre' => 'SANTA ANA TLACOTENCO'],
['idMunicipio'=>279, 'nombre' => 'CRUZTITLA'],
['idMunicipio'=>279, 'nombre' => 'ATLIMEYA'],
['idMunicipio'=>279, 'nombre' => 'ATOCTIENCO'],
['idMunicipio'=>279, 'nombre' => 'LOS PINOS (TOTULAN)'],
['idMunicipio'=>279, 'nombre' => 'XOCTONCO'],
['idMunicipio'=>279, 'nombre' => 'COZCATLAN'],
['idMunicipio'=>279, 'nombre' => 'LA HERRADURA (SEPTIMA CURVA)'],
['idMunicipio'=>279, 'nombre' => 'ZANGAHCO'],
['idMunicipio'=>279, 'nombre' => 'HUEYCOTZINGO'],
['idMunicipio'=>279, 'nombre' => 'MELHCALHCA'],
['idMunicipio'=>279, 'nombre' => 'CUAUHTEC (EL MIRADOR SANTA ANA TLACOTENCO)'],
['idMunicipio'=>279, 'nombre' => 'LA MORA'],
['idMunicipio'=>279, 'nombre' => 'METENCO'],
['idMunicipio'=>279, 'nombre' => 'TAMASQUITITLA'],
['idMunicipio'=>279, 'nombre' => 'SAN AGUSTIN EL ALTO'],
['idMunicipio'=>279, 'nombre' => 'SAN MARCOS'],
['idMunicipio'=>279, 'nombre' => 'ATLATLAUCO'],
['idMunicipio'=>279, 'nombre' => 'CUYUCALCO'],
['idMunicipio'=>279, 'nombre' => 'IZTAUHAGCA'],
['idMunicipio'=>279, 'nombre' => 'TZOTZOMACO'],
['idMunicipio'=>279, 'nombre' => 'TLATEPEXCO'],
['idMunicipio'=>279, 'nombre' => 'LAGUNILLA'],
['idMunicipio'=>279, 'nombre' => 'SAN PAOCOTITLA'],
['idMunicipio'=>279, 'nombre' => 'TLACOPAC'],
['idMunicipio'=>279, 'nombre' => 'TECOLOTZITZATZIAN (PILTONGO)'],
['idMunicipio'=>279, 'nombre' => 'TEHUISCO'],
['idMunicipio'=>279, 'nombre' => 'AHUATATAPANCO (METLALZINTLA)'],
['idMunicipio'=>279, 'nombre' => 'TEQUIANQUIZTUNCO'],
['idMunicipio'=>279, 'nombre' => 'TETEXIPEZCO'],
['idMunicipio'=>279, 'nombre' => 'TETLICUILI (EL ENCINAL)'],
['idMunicipio'=>279, 'nombre' => 'TEUHTLI'],
['idMunicipio'=>279, 'nombre' => 'TEXCALAHUITIEL'],
['idMunicipio'=>279, 'nombre' => 'TEXCAYUCA (OJO DE AGUA)'],
['idMunicipio'=>279, 'nombre' => 'TEZOMPA'],
['idMunicipio'=>279, 'nombre' => 'TEZIUHTEPEC'],
['idMunicipio'=>279, 'nombre' => 'TETZUMPA'],
['idMunicipio'=>279, 'nombre' => 'TLAXALA'],
['idMunicipio'=>279, 'nombre' => 'AHUAPAPATLAPA'],
['idMunicipio'=>279, 'nombre' => 'TETEPANCO'],
['idMunicipio'=>279, 'nombre' => 'CERRADA FRANCISCO I. MADERO'],
['idMunicipio'=>279, 'nombre' => 'SAN JOSE'],
['idMunicipio'=>279, 'nombre' => 'HUEYTEPETL'],
['idMunicipio'=>279, 'nombre' => 'COXIMALIPA'],
['idMunicipio'=>279, 'nombre' => 'TLALTEPEC (CASA DEL COMUNERO)'],
['idMunicipio'=>279, 'nombre' => 'EL TULMIAC'],
['idMunicipio'=>279, 'nombre' => 'CORRALIXPA'],
['idMunicipio'=>279, 'nombre' => 'EL RANCHO'],
['idMunicipio'=>279, 'nombre' => 'COYOCALLI'],
['idMunicipio'=>279, 'nombre' => 'TLAPALAN'],
['idMunicipio'=>279, 'nombre' => 'RETAMATITLA (TEPEHUALE)'],
['idMunicipio'=>279, 'nombre' => 'TEXALCO'],
['idMunicipio'=>279, 'nombre' => 'QUEPILCO'],
['idMunicipio'=>279, 'nombre' => 'TEXOCOCLIXPA (RANCHO SANTA ELENA)'],
['idMunicipio'=>279, 'nombre' => 'CUILOTEPEC'],
['idMunicipio'=>279, 'nombre' => 'BARRANCA SECA (POZO OCHO)'],
['idMunicipio'=>279, 'nombre' => 'TEATLACO'],
['idMunicipio'=>279, 'nombre' => 'TLALOXTOC (EJIDOS DE TECOXPA)'],
['idMunicipio'=>279, 'nombre' => 'ATUZANCO'],
['idMunicipio'=>279, 'nombre' => 'EL POTRERO'],
['idMunicipio'=>279, 'nombre' => 'JALISCO'],
['idMunicipio'=>279, 'nombre' => 'MIQUIXPA'],
['idMunicipio'=>279, 'nombre' => 'SAN LORENZO TLACOYUCAN'],
['idMunicipio'=>279, 'nombre' => 'RINCONADA DEL TEOCA'],
['idMunicipio'=>279, 'nombre' => 'TEPEPECHIMULCO'],
['idMunicipio'=>279, 'nombre' => 'TEMOCLALUCA'],
['idMunicipio'=>279, 'nombre' => 'MALACAXCO'],
['idMunicipio'=>279, 'nombre' => 'CUATLIXCO'],
['idMunicipio'=>279, 'nombre' => 'TLALOXTUTIENCO (MONTESINOS)'],
['idMunicipio'=>279, 'nombre' => 'COAMETZU'],
['idMunicipio'=>279, 'nombre' => 'CUAUHTUNCO'],
['idMunicipio'=>279, 'nombre' => 'LA ERA'],
['idMunicipio'=>279, 'nombre' => 'TEPETENCO'],
['idMunicipio'=>279, 'nombre' => 'SAN ISIDRO CUATEPEC'],
['idMunicipio'=>279, 'nombre' => 'XALUIS (IXTAHUACA)'],
['idMunicipio'=>279, 'nombre' => 'TLACAXATL (BARRIO XOCHITEPEC)'],
['idMunicipio'=>279, 'nombre' => 'TLACHACHALIPAC'],
['idMunicipio'=>279, 'nombre' => 'CAMINO REAL A TLALTENAMI'],
['idMunicipio'=>279, 'nombre' => 'MECALCO'],
['idMunicipio'=>279, 'nombre' => 'ZACATONCO'],
['idMunicipio'=>279, 'nombre' => 'XALI'],
['idMunicipio'=>279, 'nombre' => 'TEXAXAHUACALLI'],
['idMunicipio'=>279, 'nombre' => 'AGUACASOLIZTINTLA'],
['idMunicipio'=>279, 'nombre' => 'ZACAXONTLIPA'],
['idMunicipio'=>279, 'nombre' => 'SANTA CATARINA (PIEDRA BLANCA)'],
['idMunicipio'=>279, 'nombre' => 'CUAUHTETEC'],
['idMunicipio'=>279, 'nombre' => 'HUITLALPA'],
['idMunicipio'=>279, 'nombre' => 'TEXCOLIPAN'],
['idMunicipio'=>279, 'nombre' => 'TETZMITITLA'],
['idMunicipio'=>279, 'nombre' => 'TLAXIOMULCO'],
['idMunicipio'=>279, 'nombre' => 'CHICHAUHTONCO'],
['idMunicipio'=>279, 'nombre' => 'TECOLOXTITLA'],
['idMunicipio'=>279, 'nombre' => 'TAPALACO (AMACAPULTITLA)'],
['idMunicipio'=>279, 'nombre' => 'TEACALCO'],
['idMunicipio'=>279, 'nombre' => 'IZTLALCO'],
['idMunicipio'=>279, 'nombre' => 'CUAUHZONTLIPAN'],
['idMunicipio'=>279, 'nombre' => 'HUEPALTEPEC'],
['idMunicipio'=>279, 'nombre' => 'MECATLAN (RANCHO EL REFUGIO)'],
['idMunicipio'=>279, 'nombre' => 'TECUPILCO (KILOMETRO 17.5)'],
['idMunicipio'=>279, 'nombre' => 'XAXALPA'],
['idMunicipio'=>279, 'nombre' => 'XALTEPETITLA'],
['idMunicipio'=>279, 'nombre' => 'TETECOLOK'],
['idMunicipio'=>279, 'nombre' => 'TLAXICOAPA (MULOTLA)'],
['idMunicipio'=>279, 'nombre' => 'SANTA ROSA'],
['idMunicipio'=>279, 'nombre' => 'OLLA DE PIEDRA'],
['idMunicipio'=>279, 'nombre' => 'EL ZAPOTE (TECHULTEPEC)'],
['idMunicipio'=>279, 'nombre' => 'MAXULCO (BARRIO CRUZTITLA)'],
['idMunicipio'=>279, 'nombre' => 'EL PIRUL'],
['idMunicipio'=>279, 'nombre' => 'SANTA MARTA CASALAN (PROLONGACION AVENIDA MEXICO NORTE)'],
['idMunicipio'=>279, 'nombre' => 'ZACUAZTITLA'],
['idMunicipio'=>279, 'nombre' => 'RANCHO PARAISO ESCONDIDO'],
['idMunicipio'=>279, 'nombre' => 'OMAXAL'],
['idMunicipio'=>279, 'nombre' => 'MIMIRADORCO (CAMINO REAL AL MONTE)'],
['idMunicipio'=>279, 'nombre' => 'AHUATITLA'],
['idMunicipio'=>279, 'nombre' => 'TEXACAZINTLA (XACALIXPA)'],
['idMunicipio'=>279, 'nombre' => 'CHICHILECAS'],
['idMunicipio'=>279, 'nombre' => 'CAMINO A LA GRANJA'],
['idMunicipio'=>279, 'nombre' => 'CALLE CAPULINES'],
['idMunicipio'=>279, 'nombre' => 'TEMALACATL [CENTRO DE PRODUCCION LAS VIOLETAS]'],
['idMunicipio'=>279, 'nombre' => 'TEMOAYAN'],
['idMunicipio'=>279, 'nombre' => 'PROLONGACION XOLOTL'],
['idMunicipio'=>279, 'nombre' => 'ANAYELI'],
['idMunicipio'=>279, 'nombre' => 'MELIAXCO'],
['idMunicipio'=>279, 'nombre' => 'LAS CRUCES PARTE ALTA (TEHUEPANCO)'],
['idMunicipio'=>279, 'nombre' => 'CUAPALIPA'],
['idMunicipio'=>279, 'nombre' => 'TEHUISTITLA'],
['idMunicipio'=>279, 'nombre' => 'CUAXALTEPEC'],
['idMunicipio'=>279, 'nombre' => 'TENOPANTITLA'],
['idMunicipio'=>279, 'nombre' => 'OCOTELOLOCO (TLAXCANTITLA)'],
['idMunicipio'=>279, 'nombre' => 'TECPALLO'],
['idMunicipio'=>279, 'nombre' => 'NUCH HUACA (TECHINANTITLE)'],
['idMunicipio'=>279, 'nombre' => 'CUACUAHOTLIPA'],
['idMunicipio'=>279, 'nombre' => 'NACATULATLAXCO'],
['idMunicipio'=>279, 'nombre' => 'TLACOXPA (TESHUTLA)'],
['idMunicipio'=>279, 'nombre' => 'CITLALCUAC (RANCHO EL PARAISO PERDIDO)'],
['idMunicipio'=>279, 'nombre' => 'ATOCTENCO (PROLONGACION NIÑOS HEROES)'],
['idMunicipio'=>279, 'nombre' => 'PARAJE HUICALCO'],
['idMunicipio'=>279, 'nombre' => 'LOS AGUILAR'],
['idMunicipio'=>279, 'nombre' => 'TETEXALOCA'],
['idMunicipio'=>279, 'nombre' => 'PROLONGACION JUSTO SIERRA'],
['idMunicipio'=>279, 'nombre' => 'ACATLACO'],
['idMunicipio'=>279, 'nombre' => 'XALMOYO'],
['idMunicipio'=>279, 'nombre' => 'OLUCA'],
['idMunicipio'=>279, 'nombre' => 'PINO SUAREZ'],
['idMunicipio'=>279, 'nombre' => 'TLALCOXTEPEC (LA JOYA)'],
['idMunicipio'=>279, 'nombre' => 'CAMINO VIEJO A SANTA CRUZ'],
['idMunicipio'=>279, 'nombre' => 'CONCLA (CAMINO A TLALTENAMIC)'],
['idMunicipio'=>279, 'nombre' => 'TLALTENAMI'],
['idMunicipio'=>279, 'nombre' => 'MIXQUIAHUAC'],
['idMunicipio'=>279, 'nombre' => 'ZACAMOLI'],
['idMunicipio'=>279, 'nombre' => 'SANTA ANA (COOPERATIVA EJIDAL)'],
['idMunicipio'=>279, 'nombre' => 'PANUCA (KILOMETRO 27.5)'],
['idMunicipio'=>279, 'nombre' => 'TLALTEPEC'],
['idMunicipio'=>279, 'nombre' => 'CHIMEO (LAS PALMAS)'],
['idMunicipio'=>279, 'nombre' => 'EL TULMIAC [CAMPAMENTO FORESTAL]'],
['idMunicipio'=>279, 'nombre' => 'AA MILPA ALTA'],
['idMunicipio'=>279, 'nombre' => 'EL CERRITO'],
['idMunicipio'=>279, 'nombre' => 'CERRO CUAUTZIN [CAMPAMENTO FORESTAL]'],
['idMunicipio'=>279, 'nombre' => 'SAN MIGUEL (TECOXOMAYEHUALTITLA)'],
['idMunicipio'=>279, 'nombre' => 'TEXOMULCO'],
['idMunicipio'=>279, 'nombre' => 'PROLONGACION BENITO JUAREZ'],
['idMunicipio'=>279, 'nombre' => 'TLALCOCOMOYA'],
['idMunicipio'=>279, 'nombre' => 'ZOZOTLAC'],
['idMunicipio'=>279, 'nombre' => 'ATOCTENCO (TLALAXCO)'],
['idMunicipio'=>279, 'nombre' => 'TECAMAC'],
['idMunicipio'=>279, 'nombre' => 'KILOMETRO 2 (ATOCPAN-XICOMULCO)'],
['idMunicipio'=>279, 'nombre' => 'ZIHUANTEMOHUAYAN'],
['idMunicipio'=>279, 'nombre' => 'LAS ABEJAS'],
['idMunicipio'=>279, 'nombre' => 'TLATZALA'],
['idMunicipio'=>279, 'nombre' => 'TETZOMPA'],
['idMunicipio'=>279, 'nombre' => 'TUZANCO (PROLONGACION MINA)'],
['idMunicipio'=>279, 'nombre' => 'RANCHO SAN JOSE LOPEZ TREJO'],
['idMunicipio'=>279, 'nombre' => 'NINGUNO'],
['idMunicipio'=>279, 'nombre' => 'TLACOPANCO'],
['idMunicipio'=>279, 'nombre' => 'PIXUCALTITLA'],
['idMunicipio'=>279, 'nombre' => 'TOTOMACUENTLA'],
['idMunicipio'=>279, 'nombre' => 'PROLONGACION VERACRUZ SUR'],
['idMunicipio'=>279, 'nombre' => 'JOYAS PARTE ALTA'],
['idMunicipio'=>279, 'nombre' => 'CAMINO DE LA AMISTAD'],
['idMunicipio'=>279, 'nombre' => 'ACUEXCOMATL'],
['idMunicipio'=>279, 'nombre' => 'TLALCOXTEPEC (PROLONGACION JUAN ESCUTIA)'],
['idMunicipio'=>279, 'nombre' => 'SAN ANTONIO CUILOTEPEC'],
['idMunicipio'=>279, 'nombre' => 'TENICHCALCO'],
['idMunicipio'=>279, 'nombre' => 'SAN NICOLAS TETELCO'],
['idMunicipio'=>279, 'nombre' => 'EL TEJOCOTE'],
['idMunicipio'=>279, 'nombre' => 'EJIDOS TECOXPA'],
['idMunicipio'=>279, 'nombre' => 'CERRADA ARBOLEDAS'],
['idMunicipio'=>279, 'nombre' => 'EMILIANO ZAPATA (AVENIDA EL CERRO)'],
['idMunicipio'=>279, 'nombre' => 'CORRALTITLA'],
['idMunicipio'=>279, 'nombre' => 'TEPANOCO'],
['idMunicipio'=>279, 'nombre' => 'PROLONGACION SINALOA NORTE'],
['idMunicipio'=>279, 'nombre' => 'SANTA MARTA (AVENIDA TLAXCALA)'],
['idMunicipio'=>279, 'nombre' => 'ZACATIPLA'],
['idMunicipio'=>279, 'nombre' => 'SANTA MARTA XOLCO'],
['idMunicipio'=>279, 'nombre' => 'CERRADA TEHUACAN'],
['idMunicipio'=>279, 'nombre' => 'VILLA HERMOSA'],
['idMunicipio'=>279, 'nombre' => 'TOTOXHPA (CERRADA CULIACAN)'],
['idMunicipio'=>279, 'nombre' => 'CERRADA BELISARIO DOMINGUEZ'],
['idMunicipio'=>279, 'nombre' => 'NUCHTLA'],
['idMunicipio'=>279, 'nombre' => 'TEHUIZCO'],
['idMunicipio'=>279, 'nombre' => 'ACHAYATIPAC'],
['idMunicipio'=>279, 'nombre' => 'AYOTEPEC'],
['idMunicipio'=>279, 'nombre' => 'OCHPANTENCO'],
['idMunicipio'=>279, 'nombre' => 'ERMITA DEL CALVARIO'],
['idMunicipio'=>279, 'nombre' => 'LA VIRGEN'],
['idMunicipio'=>279, 'nombre' => 'MATLAHUACALOCA'],
['idMunicipio'=>279, 'nombre' => 'TULA (HUIXTOTLAZINTLA)'],
['idMunicipio'=>279, 'nombre' => 'TEQUIMILPA'],
['idMunicipio'=>279, 'nombre' => 'TLATLAPANTUNCO'],
['idMunicipio'=>279, 'nombre' => 'SAN AGUSTIN'],
['idMunicipio'=>279, 'nombre' => 'LA CONCEPCION'],
['idMunicipio'=>279, 'nombre' => 'LOS ANGELES'],
['idMunicipio'=>279, 'nombre' => 'TEZONTLIPAC'],
['idMunicipio'=>279, 'nombre' => 'CAMINO A TELERA'],
['idMunicipio'=>279, 'nombre' => 'TLALZONCO'],
['idMunicipio'=>279, 'nombre' => 'TEMAZCALTITLA'],
['idMunicipio'=>279, 'nombre' => 'PROLONGACION 5 DE MAYO'],
['idMunicipio'=>279, 'nombre' => 'CHAUTONCO'],
['idMunicipio'=>279, 'nombre' => 'TEXOTITLA'],
['idMunicipio'=>279, 'nombre' => 'COATEPEC'],
['idMunicipio'=>279, 'nombre' => 'OCOTITLA'],
['idMunicipio'=>279, 'nombre' => 'TOLTECAS PARTE ALTA (CERRADA JACARANDAS)'],
['idMunicipio'=>279, 'nombre' => 'XOCHIATLACO'],
['idMunicipio'=>279, 'nombre' => 'HUACALTUNCO'],
['idMunicipio'=>279, 'nombre' => 'LAS PALMAS'],
['idMunicipio'=>279, 'nombre' => 'TLAHUIZTPA'],
['idMunicipio'=>279, 'nombre' => 'ZACACALI'],
['idMunicipio'=>279, 'nombre' => 'TEPENAHUAC [CENTRO DE EDUCACION AMBIENTAL]'],
['idMunicipio'=>279, 'nombre' => 'CAMINO VIEJO A TLALTENAMIC'],
['idMunicipio'=>280, 'nombre' => 'ALVARO OBREGON'],
['idMunicipio'=>280, 'nombre' => 'CUAUHTLAMILA'],
['idMunicipio'=>280, 'nombre' => 'AMPLIACION SAN BERNABE (TENANGO)'],
['idMunicipio'=>280, 'nombre' => 'CAMINO A LA BANDERA'],
['idMunicipio'=>280, 'nombre' => 'TIXIMALOYA'],
['idMunicipio'=>280, 'nombre' => 'EL ERMITAÑO (PARAJE EL CHIPIL)'],
['idMunicipio'=>280, 'nombre' => 'TEXCALATLACO'],
['idMunicipio'=>280, 'nombre' => 'EL CAMPANARIO'],
['idMunicipio'=>280, 'nombre' => 'APAPAXTLA'],
['idMunicipio'=>281, 'nombre' => 'TLAHUAC'],
['idMunicipio'=>281, 'nombre' => 'SAN ANDRES MIXQUIC'],
['idMunicipio'=>281, 'nombre' => 'SAN JUAN IXTAYOPAN'],
['idMunicipio'=>281, 'nombre' => 'SAN NICOLAS TETELCO'],
['idMunicipio'=>281, 'nombre' => 'SANTA CATARINA YECAHUITZOTL'],
['idMunicipio'=>281, 'nombre' => 'SAN MIGUEL'],
['idMunicipio'=>281, 'nombre' => 'TABLA LOS POZOS'],
['idMunicipio'=>281, 'nombre' => 'MESITA DEL CAPULIN'],
['idMunicipio'=>281, 'nombre' => 'OJO DE AGUA'],
['idMunicipio'=>281, 'nombre' => 'SAN MIGUEL (CHINAMPAS)'],
['idMunicipio'=>281, 'nombre' => 'SANTA CATARINA (TEQUEXQUIPA)'],
['idMunicipio'=>281, 'nombre' => 'XILA'],
['idMunicipio'=>281, 'nombre' => 'EL TETECON (EL SOLITARIO)'],
['idMunicipio'=>281, 'nombre' => 'CHINAMPA SAN JUAN'],
['idMunicipio'=>281, 'nombre' => 'FIN DE GALEANA'],
['idMunicipio'=>281, 'nombre' => 'PUENTE DE TUBO'],
['idMunicipio'=>281, 'nombre' => 'PARAJE XOMETITLA'],
['idMunicipio'=>281, 'nombre' => 'SAN IGNACIO DE LOYOLA'],
['idMunicipio'=>281, 'nombre' => 'PARAJE AYECAC'],
['idMunicipio'=>281, 'nombre' => 'LA CIENEGA'],
['idMunicipio'=>281, 'nombre' => 'CHINAMPAS TETELCO'],
['idMunicipio'=>281, 'nombre' => 'LOMAS DE XOCOTLAN'],
['idMunicipio'=>281, 'nombre' => 'SANTA CATARINA [LIENZO CHARRO]'],
['idMunicipio'=>281, 'nombre' => 'TIERRA BLANCA PARTE ALTA'],
['idMunicipio'=>281, 'nombre' => 'RANCHO LAS SIETE YUNTAS'],
['idMunicipio'=>281, 'nombre' => 'LAS TABLAS'],
['idMunicipio'=>281, 'nombre' => 'MINA XALTEPEC'],
['idMunicipio'=>281, 'nombre' => 'MINA LA ESTANCIA'],
['idMunicipio'=>281, 'nombre' => 'MINA TEXCOCATITLA'],
['idMunicipio'=>281, 'nombre' => 'CAMINO A TLALTENCO'],
['idMunicipio'=>281, 'nombre' => 'PROLONGACION PEÑA ALTA'],
['idMunicipio'=>281, 'nombre' => 'RANCHO LOS POLLITOS'],
['idMunicipio'=>281, 'nombre' => 'EL RANCHO (RANCHO LA PISTOLA DEL EJIDO)'],
['idMunicipio'=>281, 'nombre' => 'TABLA TELOCUATITLA'],
['idMunicipio'=>281, 'nombre' => 'EL PATO'],
['idMunicipio'=>281, 'nombre' => 'TABLA 2-4'],
['idMunicipio'=>281, 'nombre' => 'MONSERRAT (ARENALES OAXACA)'],
['idMunicipio'=>281, 'nombre' => 'EL PARAISO (MECOXTLA)'],
['idMunicipio'=>281, 'nombre' => 'EL ZAPOTE (COLONIA EJIDAL)'],
['idMunicipio'=>281, 'nombre' => 'AMPLIACION SAN MIGUEL'],
['idMunicipio'=>281, 'nombre' => 'NINGUNO'],
['idMunicipio'=>281, 'nombre' => 'CAMINO A LAS MINAS'],
['idMunicipio'=>281, 'nombre' => 'XALPA'],
['idMunicipio'=>281, 'nombre' => 'DESARROLLO ECO TURISTICO REYES FLORES'],
['idMunicipio'=>281, 'nombre' => 'TERCER CALLEJON DE CALVARIO'],
['idMunicipio'=>281, 'nombre' => 'PUERTANTITLA (CAMINO AL CERRO)'],
['idMunicipio'=>281, 'nombre' => 'PROLONGACION EL ROSARIO'],
['idMunicipio'=>281, 'nombre' => 'LA NOPALERA'],
['idMunicipio'=>281, 'nombre' => 'TERCERA CERRADA DE MAZATEPEC'],
['idMunicipio'=>281, 'nombre' => 'BUGAMBILIAS'],
['idMunicipio'=>281, 'nombre' => 'TEZONTITLA'],
['idMunicipio'=>281, 'nombre' => 'XALATLAYCO'],
['idMunicipio'=>282, 'nombre' => 'TLALPAN'],
['idMunicipio'=>282, 'nombre' => 'PARRES (EL GUARDA)'],
['idMunicipio'=>282, 'nombre' => 'SAN MIGUEL AJUSCO'],
['idMunicipio'=>282, 'nombre' => 'SAN MIGUEL TOPILEJO'],
['idMunicipio'=>282, 'nombre' => 'AMPLIACION LAS CRUCES'],
['idMunicipio'=>282, 'nombre' => 'LA CIMA UNO [CAMPAMENTO FORESTAL]'],
['idMunicipio'=>282, 'nombre' => 'APAPAXTLES'],
['idMunicipio'=>282, 'nombre' => 'PARAJE CERCATENCO'],
['idMunicipio'=>282, 'nombre' => 'LLANO DE CANTIMPLORA'],
['idMunicipio'=>282, 'nombre' => 'CASA SOLAR'],
['idMunicipio'=>282, 'nombre' => 'ACUEDUCTO'],
['idMunicipio'=>282, 'nombre' => 'LA CIMA DOS [CAMPAMENTO FORESTAL]'],
['idMunicipio'=>282, 'nombre' => 'CUAMINO'],
['idMunicipio'=>282, 'nombre' => 'CORENA REGIONAL 2 (EL CRUCERO)'],
['idMunicipio'=>282, 'nombre' => 'ESTACION LA CIMA'],
['idMunicipio'=>282, 'nombre' => 'MEZONTEPEC [CAMPAMENTO FORESTAL]'],
['idMunicipio'=>282, 'nombre' => 'XACATIXTLA (GRANJA LA GARRIGA)'],
['idMunicipio'=>282, 'nombre' => 'HEROES DE 1910'],
['idMunicipio'=>282, 'nombre' => 'LAS RAICES'],
['idMunicipio'=>282, 'nombre' => 'KILOMETRO 38'],
['idMunicipio'=>282, 'nombre' => 'KILOMETRO 36.5 (EL CRUCERO)'],
['idMunicipio'=>282, 'nombre' => 'LAS MARAVILLAS (KILOMETRO 37)'],
['idMunicipio'=>282, 'nombre' => 'KILOMETRO 33.5'],
['idMunicipio'=>282, 'nombre' => 'LOMAS DE TEPEMECATL'],
['idMunicipio'=>282, 'nombre' => 'EL OYAMEL'],
['idMunicipio'=>282, 'nombre' => 'EL PARAISO'],
['idMunicipio'=>282, 'nombre' => 'PENTATLON'],
['idMunicipio'=>282, 'nombre' => 'PIEDRA LARGA'],
['idMunicipio'=>282, 'nombre' => 'PIEDRAS BLANCAS'],
['idMunicipio'=>282, 'nombre' => 'RANCHO APRISCO CIMA'],
['idMunicipio'=>282, 'nombre' => 'RANCHO RAMIREZ'],
['idMunicipio'=>282, 'nombre' => 'RANCHO ROBERTO CAMACHO'],
['idMunicipio'=>282, 'nombre' => 'LA CUEVA DEL OSO'],
['idMunicipio'=>282, 'nombre' => 'LA FORTALEZA'],
['idMunicipio'=>282, 'nombre' => 'RANCHO SANTISIMA TRINIDAD'],
['idMunicipio'=>282, 'nombre' => 'SEMINARIO NAZARENO'],
['idMunicipio'=>282, 'nombre' => 'EL PEDREGAL'],
['idMunicipio'=>282, 'nombre' => 'EL SIFON'],
['idMunicipio'=>282, 'nombre' => 'KILOMETRO 17 (CIRCUITO AJUSCO)'],
['idMunicipio'=>282, 'nombre' => 'RANCHO LAS TROJES'],
['idMunicipio'=>282, 'nombre' => 'XALCUITONGO (LA ASUNCION)'],
['idMunicipio'=>282, 'nombre' => 'LA TRINIDAD'],
['idMunicipio'=>282, 'nombre' => 'SIETE OCOTES'],
['idMunicipio'=>282, 'nombre' => 'QUINTA GALA (KILOMETRO 35)'],
['idMunicipio'=>282, 'nombre' => 'EL CHARCO'],
['idMunicipio'=>282, 'nombre' => 'RANCHO KYALAMI'],
['idMunicipio'=>282, 'nombre' => 'LOS SAUCES'],
['idMunicipio'=>282, 'nombre' => 'RANCHO SAN FRANCISCO'],
['idMunicipio'=>282, 'nombre' => 'LA TROJE'],
['idMunicipio'=>282, 'nombre' => 'EL COFRECITO'],
['idMunicipio'=>282, 'nombre' => 'RANCHO ESPIRIDION'],
['idMunicipio'=>282, 'nombre' => 'RANCHO LOS COMPADRES'],
['idMunicipio'=>282, 'nombre' => 'RANCHO EL PARAISO'],
['idMunicipio'=>282, 'nombre' => 'RANCHO LOS PIONEROS'],
['idMunicipio'=>282, 'nombre' => 'EL DIVISADERO'],
['idMunicipio'=>282, 'nombre' => 'CAMINO VIEJO A SAN ANDRES'],
['idMunicipio'=>282, 'nombre' => 'RANCHO SAN NICOLAS'],
['idMunicipio'=>282, 'nombre' => 'EL ARENAL'],
['idMunicipio'=>282, 'nombre' => 'CUANEJAQUE'],
['idMunicipio'=>282, 'nombre' => 'EL OYAMEYO'],
['idMunicipio'=>282, 'nombre' => 'PARADA OYAMEYO (KILOMETRO 31.5)'],
['idMunicipio'=>282, 'nombre' => 'LA CAMPANA (KILOMETRO 12)'],
['idMunicipio'=>282, 'nombre' => 'LA RUFINA'],
['idMunicipio'=>282, 'nombre' => 'NOPALTITLA'],
['idMunicipio'=>282, 'nombre' => 'TRES CABAÑAS'],
['idMunicipio'=>282, 'nombre' => 'EL ALAMBRADO'],
['idMunicipio'=>282, 'nombre' => 'ESTUDIOS AJUSCO'],
['idMunicipio'=>282, 'nombre' => 'EL ABREVADERO'],
['idMunicipio'=>282, 'nombre' => 'XOMULCO (OYAMERTONCO)'],
['idMunicipio'=>282, 'nombre' => 'RANCHO SANTA ROSA'],
['idMunicipio'=>282, 'nombre' => 'KILOMETRO 34 CIRCUITO AJUSCO'],
['idMunicipio'=>282, 'nombre' => 'LOS CABALLOS'],
['idMunicipio'=>282, 'nombre' => 'LA BOLA'],
['idMunicipio'=>282, 'nombre' => 'RANCHO CHICO'],
['idMunicipio'=>282, 'nombre' => 'RANCHO LOPEZ MARQUEZ'],
['idMunicipio'=>282, 'nombre' => 'RANCHO LOS CEDROS DEL ABUELO'],
['idMunicipio'=>282, 'nombre' => 'HARO'],
['idMunicipio'=>282, 'nombre' => 'QUINTA SANTA ROSA'],
['idMunicipio'=>282, 'nombre' => 'LA MORUCHA'],
['idMunicipio'=>282, 'nombre' => 'RANCHO SAN PATRICIO'],
['idMunicipio'=>282, 'nombre' => 'BARRANQUILLA'],
['idMunicipio'=>282, 'nombre' => 'LA CAPILLA'],
['idMunicipio'=>282, 'nombre' => 'RANCHO MEZONTEPEC'],
['idMunicipio'=>282, 'nombre' => 'RANCHO LLANO DE VIDRIO'],
['idMunicipio'=>282, 'nombre' => 'LLANITO LARGO [CAMPAMENTO FORESTAL]'],
['idMunicipio'=>282, 'nombre' => 'AGUATENCO'],
['idMunicipio'=>282, 'nombre' => 'EL SICOMORO'],
['idMunicipio'=>282, 'nombre' => 'TLAMENELOLPA (LOS ENCINOS)'],
['idMunicipio'=>282, 'nombre' => 'PREDIO TEPETZINTLA'],
['idMunicipio'=>282, 'nombre' => 'LA CANDELARIA'],
['idMunicipio'=>282, 'nombre' => 'LA PROVIDENCIA'],
['idMunicipio'=>282, 'nombre' => 'FINCA TRANCAS'],
['idMunicipio'=>282, 'nombre' => 'KILOMETRO 32.3'],
['idMunicipio'=>282, 'nombre' => 'TEMAXCATITLA (KILOMETRO 32.2)'],
['idMunicipio'=>282, 'nombre' => 'PARAJE DE APANTENCO'],
['idMunicipio'=>282, 'nombre' => 'TOTOAPAN'],
['idMunicipio'=>282, 'nombre' => 'COLONIA OCOTLA'],
['idMunicipio'=>282, 'nombre' => 'KILOMETRO 29.5'],
['idMunicipio'=>282, 'nombre' => 'KILOMETRO 30'],
['idMunicipio'=>282, 'nombre' => 'KILOMETRO 30.5'],
['idMunicipio'=>282, 'nombre' => 'JOSE MARIA MORELOS'],
['idMunicipio'=>282, 'nombre' => 'LOS EUCALIPTOS'],
['idMunicipio'=>282, 'nombre' => 'OCOTLA CHICO'],
['idMunicipio'=>282, 'nombre' => 'PARAJE ATONCO'],
['idMunicipio'=>282, 'nombre' => 'LA HERRADURA'],
['idMunicipio'=>282, 'nombre' => 'CARRETERA AL AJUSCO'],
['idMunicipio'=>282, 'nombre' => 'EL PEDREGAL'],
['idMunicipio'=>282, 'nombre' => 'CHAHUALIXCANTITLA'],
['idMunicipio'=>282, 'nombre' => 'LOMAS DE SAN JOSE'],
['idMunicipio'=>282, 'nombre' => 'ACUEDUCTO (PEDRO MORENO)'],
['idMunicipio'=>282, 'nombre' => 'COLONIA SAN JUAN'],
['idMunicipio'=>282, 'nombre' => 'COLONIA AGUAYOTO'],
['idMunicipio'=>282, 'nombre' => 'LOS ENCINOS'],
['idMunicipio'=>282, 'nombre' => 'KILOMETRO 32.1'],
['idMunicipio'=>282, 'nombre' => 'LIENZO CHARRO PEPE CASTRO'],
['idMunicipio'=>282, 'nombre' => 'TRES VIENTOS'],
['idMunicipio'=>282, 'nombre' => 'JALTOMATITLA'],
['idMunicipio'=>282, 'nombre' => 'KILOMETRO 7.5 (CIRCUITO AJUSCO)'],
['idMunicipio'=>282, 'nombre' => 'CAMINO A LA VENTA'],
['idMunicipio'=>282, 'nombre' => 'LA MONERA'],
['idMunicipio'=>282, 'nombre' => 'EL TIANGUILLO (KILOMETRO 19.5)'],
['idMunicipio'=>282, 'nombre' => 'CRIADERO KODIK'],
['idMunicipio'=>282, 'nombre' => 'CAMINO CANTERA CANTIL'],
['idMunicipio'=>282, 'nombre' => 'CORTIJO SAN HIGINIO'],
['idMunicipio'=>282, 'nombre' => 'PLANTA ABASOLO'],
['idMunicipio'=>282, 'nombre' => 'CUAUHTENCO'],
['idMunicipio'=>282, 'nombre' => 'TEPOZAN [PARQUE ECOTURISTICO]'],
['idMunicipio'=>282, 'nombre' => 'EJIDOS DE SAN ANDRES TOTOLTEPEC'],
['idMunicipio'=>282, 'nombre' => 'AREA DE LOS VENADOS (LA SIREFA)'],
['idMunicipio'=>282, 'nombre' => 'PROLONGACION NARCISO MENDOZA'],
['idMunicipio'=>282, 'nombre' => 'PROLONGACION ACUEDUCTO'],
['idMunicipio'=>282, 'nombre' => 'GRANJA LOS PINOS'],
['idMunicipio'=>282, 'nombre' => 'RANCHO EL TORDI...YO'],
['idMunicipio'=>282, 'nombre' => 'AGUA GRANDE [PARQUE RECREATIVO]'],
['idMunicipio'=>282, 'nombre' => 'RANCHO YAMEL'],
['idMunicipio'=>282, 'nombre' => 'KILOMETRO 14.5'],
['idMunicipio'=>282, 'nombre' => 'EL OYAMEL'],
['idMunicipio'=>282, 'nombre' => 'RANCHO TRES HERMANOS'],
['idMunicipio'=>282, 'nombre' => 'LAS CRUCES'],
['idMunicipio'=>282, 'nombre' => 'RANCHO MATAMOROS'],
['idMunicipio'=>282, 'nombre' => 'RANCHO VALENTINA'],
['idMunicipio'=>282, 'nombre' => 'ERMITA AJUSCO'],
['idMunicipio'=>282, 'nombre' => 'EL CEDRAL'],
['idMunicipio'=>282, 'nombre' => 'LAS CALAVERAS (DOÑA CRISTY)'],
['idMunicipio'=>282, 'nombre' => 'LOS TLAPANCOS'],
['idMunicipio'=>282, 'nombre' => 'CARRETERA AL AJUSCO II'],
['idMunicipio'=>282, 'nombre' => 'LAS CANTERAS'],
['idMunicipio'=>282, 'nombre' => 'CAMINO ANTIGUO A CUERNAVACA'],
['idMunicipio'=>282, 'nombre' => 'CAÑADA DEL ACUEDUCTO'],
['idMunicipio'=>282, 'nombre' => 'ACUEDUCTO 1RA. SECCION'],
['idMunicipio'=>282, 'nombre' => 'EL CAMPO'],
['idMunicipio'=>282, 'nombre' => 'CUATZONTLE'],
['idMunicipio'=>282, 'nombre' => 'EL ARCOIRIS'],
['idMunicipio'=>282, 'nombre' => 'TIXTAPALTONGO (LOMA DE AHUAYOTO)'],
['idMunicipio'=>282, 'nombre' => 'RANCHO AHUAYOTO'],
['idMunicipio'=>282, 'nombre' => 'OYAMETONCO'],
['idMunicipio'=>282, 'nombre' => 'CANSACABALLOS'],
['idMunicipio'=>282, 'nombre' => 'LOS ARCOS'],
['idMunicipio'=>282, 'nombre' => 'CABAÑA BUENAVISTA'],
['idMunicipio'=>282, 'nombre' => 'OJO DE AGUA'],
['idMunicipio'=>282, 'nombre' => 'TEPELANCOXTLA'],
['idMunicipio'=>282, 'nombre' => 'SAN AGUSTIN'],
['idMunicipio'=>282, 'nombre' => 'ISPANCOLOHUIA'],
['idMunicipio'=>282, 'nombre' => 'PARAJE TLALMENELOLPA'],
['idMunicipio'=>282, 'nombre' => 'TETEOCOTLA'],
['idMunicipio'=>282, 'nombre' => 'PARAJE EL TEZONTLE ACOPIAXCO'],
['idMunicipio'=>282, 'nombre' => 'RANCHO VIEJO'],
['idMunicipio'=>282, 'nombre' => 'PARAJE EL NEGRO'],
['idMunicipio'=>282, 'nombre' => 'CAMINO VIEJO A CUERNAVACA'],
['idMunicipio'=>282, 'nombre' => 'OLOLICA (LOLOIGQUE)'],
['idMunicipio'=>282, 'nombre' => 'NINGUNO'],
['idMunicipio'=>282, 'nombre' => 'KILOMETRO 31'],
['idMunicipio'=>282, 'nombre' => 'ACOPIAXCO [CAMPAMENTO FORESTAL]'],
['idMunicipio'=>282, 'nombre' => 'CERRO PELADO [CAMPAMENTO FORESTAL]'],
['idMunicipio'=>282, 'nombre' => 'LA ROSA [CAMPAMENTO FORESTAL]'],
['idMunicipio'=>282, 'nombre' => 'LA GLORIETA'],
['idMunicipio'=>282, 'nombre' => 'PARAJE ALTAVISTA'],
['idMunicipio'=>282, 'nombre' => 'LA LOMA'],
['idMunicipio'=>282, 'nombre' => 'LA REJA'],
['idMunicipio'=>282, 'nombre' => 'POPOCOTLA'],
['idMunicipio'=>282, 'nombre' => 'COLONIA CUAUHTENCO (KILOMETRO 27)'],
['idMunicipio'=>282, 'nombre' => 'KILOMETRO 28 SUR'],
['idMunicipio'=>282, 'nombre' => 'PARAJE BUENAVISTA'],
['idMunicipio'=>282, 'nombre' => 'LOS ENCINOS [RANCHO]'],
['idMunicipio'=>282, 'nombre' => 'TEZONTITLA'],
['idMunicipio'=>282, 'nombre' => 'XICTONTLE [CAMPAMENTO FORESTAL]'],
['idMunicipio'=>282, 'nombre' => 'RANCHO TEO'],
['idMunicipio'=>282, 'nombre' => 'PIEDRA SUELTA'],
['idMunicipio'=>282, 'nombre' => 'EL CRISTAL'],
['idMunicipio'=>282, 'nombre' => 'EL RETIRO'],
['idMunicipio'=>282, 'nombre' => 'LA NUBE'],
['idMunicipio'=>282, 'nombre' => 'LAS CASTAÑAS'],
['idMunicipio'=>282, 'nombre' => 'SAN CARLOS'],
['idMunicipio'=>282, 'nombre' => 'RANCHO CHATO'],
['idMunicipio'=>282, 'nombre' => 'EL CAPRICHO'],
['idMunicipio'=>282, 'nombre' => 'EL SILLAR'],
['idMunicipio'=>282, 'nombre' => 'LA QUINTA ESTACION'],
['idMunicipio'=>282, 'nombre' => 'RANCHO NEVADO'],
['idMunicipio'=>282, 'nombre' => 'LA SOLEDAD'],
['idMunicipio'=>282, 'nombre' => 'CASAS BLANCAS'],
['idMunicipio'=>282, 'nombre' => 'LAS TINAJAS'],
['idMunicipio'=>282, 'nombre' => 'EL ARCO AMARILLO'],
['idMunicipio'=>282, 'nombre' => 'EL GUARDITA'],
['idMunicipio'=>282, 'nombre' => 'EL CAPRICHO'],
['idMunicipio'=>282, 'nombre' => 'TLAYELPA'],
['idMunicipio'=>283, 'nombre' => 'XOCHIMILCO'],
['idMunicipio'=>283, 'nombre' => 'TEPEMIMILCO'],
['idMunicipio'=>283, 'nombre' => 'IXOTITLA'],
['idMunicipio'=>283, 'nombre' => 'PARAJE LILA (EL LADRILLO)'],
['idMunicipio'=>283, 'nombre' => 'PARAJE TEXHUILO'],
['idMunicipio'=>283, 'nombre' => 'ZACAPA'],
['idMunicipio'=>283, 'nombre' => 'BARRIO SAN ANTONIO (CRUZ MONTE)'],
['idMunicipio'=>283, 'nombre' => 'TEPEPAN'],
['idMunicipio'=>283, 'nombre' => 'AMPLIACION CHALMITA'],
['idMunicipio'=>283, 'nombre' => 'EL MIRADOR (TETEXALOCA)'],
['idMunicipio'=>283, 'nombre' => 'TEPEXOMULCO'],
['idMunicipio'=>283, 'nombre' => 'TLACHIULTEPEC DE AHUAYUCAN (LAS MALVINAS)'],
['idMunicipio'=>283, 'nombre' => 'TEPETITLA (TLACOXPAN)'],
['idMunicipio'=>283, 'nombre' => 'TLACUALLELI (EL CALVARIO)'],
['idMunicipio'=>283, 'nombre' => 'TLALTEPETLA (TEHUISTITLA)'],
['idMunicipio'=>283, 'nombre' => 'TLALATLACO'],
['idMunicipio'=>283, 'nombre' => 'TLATZALA (CUAYUCA)'],
['idMunicipio'=>283, 'nombre' => 'ISLA DE LAS MUÑECAS'],
['idMunicipio'=>283, 'nombre' => 'TEPUENTE'],
['idMunicipio'=>283, 'nombre' => 'AHUATITLA'],
['idMunicipio'=>283, 'nombre' => 'TIPIPILI'],
['idMunicipio'=>283, 'nombre' => 'TOCHUCA (SAN SALVADOR)'],
['idMunicipio'=>283, 'nombre' => 'TECANCO'],
['idMunicipio'=>283, 'nombre' => 'PEPELAXTLA'],
['idMunicipio'=>283, 'nombre' => 'TECACALANGO'],
['idMunicipio'=>283, 'nombre' => 'TZOMPOLE'],
['idMunicipio'=>283, 'nombre' => 'CACALCO (TEPEXTENCO)'],
['idMunicipio'=>283, 'nombre' => 'TEXALCO (JOYAS DE TEXALCO)'],
['idMunicipio'=>283, 'nombre' => 'APATLACO'],
['idMunicipio'=>283, 'nombre' => 'PARAJE DE LA CIENEGA'],
['idMunicipio'=>283, 'nombre' => 'PARAJE LOS ESCONDIDOS'],
['idMunicipio'=>283, 'nombre' => 'KILOMETRO 26'],
['idMunicipio'=>283, 'nombre' => 'TLAPIZATIL (PUENTE DE URRUTIA)'],
['idMunicipio'=>283, 'nombre' => 'TEPEXOMULCO LAS ROCAS'],
['idMunicipio'=>283, 'nombre' => 'OCOTITLA TEPACHUXIAC'],
['idMunicipio'=>283, 'nombre' => 'TECUYO'],
['idMunicipio'=>283, 'nombre' => 'HUALPALCALTEPEC'],
['idMunicipio'=>283, 'nombre' => 'ATOTLE'],
['idMunicipio'=>283, 'nombre' => 'LOS TEJOCOTES'],
['idMunicipio'=>283, 'nombre' => 'GRANJA R.R. (LOS CIRUELOS)'],
['idMunicipio'=>283, 'nombre' => 'TEPEPATLAXTLE'],
['idMunicipio'=>283, 'nombre' => 'TIXCULCO'],
['idMunicipio'=>283, 'nombre' => 'TECOEXCONTITLA'],
['idMunicipio'=>283, 'nombre' => 'QUINTA PATRICIA'],
['idMunicipio'=>283, 'nombre' => 'EL POTRERO (BOSQUES DE LA PAZ)'],
['idMunicipio'=>283, 'nombre' => 'PARAJE TEPANYECAC'],
['idMunicipio'=>283, 'nombre' => 'TEPEPULA'],
['idMunicipio'=>283, 'nombre' => 'LA ANGOSTURA'],
['idMunicipio'=>283, 'nombre' => 'SIHUATLIXPA'],
['idMunicipio'=>283, 'nombre' => 'CUATIXI'],
['idMunicipio'=>283, 'nombre' => 'PARAJE ZACAPA'],
['idMunicipio'=>283, 'nombre' => 'SANTA CATARINA (PIEDRA BLANCA)'],
['idMunicipio'=>283, 'nombre' => 'HUEPALTEPEC'],
['idMunicipio'=>283, 'nombre' => 'TECUANATLA (ARENAL PAPANCO)'],
['idMunicipio'=>283, 'nombre' => 'TEPEPECALACHICO (INOPILCO)'],
['idMunicipio'=>283, 'nombre' => 'RANCHO LA FLOR'],
['idMunicipio'=>283, 'nombre' => 'LOS CEDROS'],
['idMunicipio'=>283, 'nombre' => 'TEPECLITE'],
['idMunicipio'=>283, 'nombre' => 'ACALIPA'],
['idMunicipio'=>283, 'nombre' => 'AMPLIACION BUGAMBILIAS (NAUHTECPAN)'],
['idMunicipio'=>283, 'nombre' => 'TEPEYECAC (EL ARENAL)'],
['idMunicipio'=>283, 'nombre' => 'TEPEXOMULCO (KILOMETRO 27.8)'],
['idMunicipio'=>283, 'nombre' => 'IXCUICUILCO'],
['idMunicipio'=>283, 'nombre' => 'CHALMA (AVENIDA DE LAS TORRES)'],
['idMunicipio'=>283, 'nombre' => 'CORRALON POLICIA FEDERAL DE CAMINOS'],
['idMunicipio'=>283, 'nombre' => 'COCOPALCUAUTLA'],
['idMunicipio'=>283, 'nombre' => 'PARADA DEL CONEJO'],
['idMunicipio'=>283, 'nombre' => 'TECANCO'],
['idMunicipio'=>283, 'nombre' => 'ATLAXCO'],
['idMunicipio'=>283, 'nombre' => 'BARRIO NOCHICALA'],
['idMunicipio'=>283, 'nombre' => 'EL CEDRAL'],
['idMunicipio'=>283, 'nombre' => 'AHUATITLA (TEXCOPAXULI)'],
['idMunicipio'=>283, 'nombre' => 'TIZICLIPA'],
['idMunicipio'=>283, 'nombre' => 'ATENCO (TLAQUILPA)'],
['idMunicipio'=>283, 'nombre' => 'NAXAYOPA'],
['idMunicipio'=>283, 'nombre' => 'COAPANTITLA'],
['idMunicipio'=>283, 'nombre' => 'SAN MARTIN'],
['idMunicipio'=>283, 'nombre' => 'FRANCISCO VILLA (TEPEJOYUCA)'],
['idMunicipio'=>283, 'nombre' => 'PANTIAGUA'],
['idMunicipio'=>283, 'nombre' => 'CHILILICO'],
['idMunicipio'=>283, 'nombre' => 'CAMINO AL PANTEON (LAS CRUCES)'],
['idMunicipio'=>283, 'nombre' => 'TEXOPANTITLA (CHOCOLINES)'],
['idMunicipio'=>283, 'nombre' => 'ILIMUNXUTITLA'],
['idMunicipio'=>283, 'nombre' => 'TLACOMULCO (KILOMETRO 25.5)'],
['idMunicipio'=>283, 'nombre' => 'LA CIENEGA'],
['idMunicipio'=>283, 'nombre' => 'LOS PINOS (TECACAHUACO)'],
['idMunicipio'=>283, 'nombre' => 'TEMAMATLA'],
['idMunicipio'=>283, 'nombre' => 'COLEXCO (TENOCHTITLAN)'],
['idMunicipio'=>283, 'nombre' => 'MILAHUAYTITLA'],
['idMunicipio'=>283, 'nombre' => 'PARAJE NOCHICALA'],
['idMunicipio'=>283, 'nombre' => 'SAN JUAN DIEGO (MATLACUAITLA)'],
['idMunicipio'=>283, 'nombre' => 'PARAJE TLAHUITECO'],
['idMunicipio'=>283, 'nombre' => 'MOYOCALCO'],
['idMunicipio'=>283, 'nombre' => 'CUAHUTICULTITLA'],
['idMunicipio'=>283, 'nombre' => 'TIZILINGO'],
['idMunicipio'=>283, 'nombre' => 'ALCANFORES'],
['idMunicipio'=>283, 'nombre' => 'BOSQUES DE LA PAZ'],
['idMunicipio'=>283, 'nombre' => 'CONTLALCO'],
['idMunicipio'=>283, 'nombre' => 'TLALMELACA'],
['idMunicipio'=>283, 'nombre' => 'XOMETITLA (TLALITENCO)'],
['idMunicipio'=>283, 'nombre' => 'ZACAXONTLICPA'],
['idMunicipio'=>284, 'nombre' => 'BENITO JUAREZ'],
['idMunicipio'=>285, 'nombre' => 'CUAUHTEMOC'],
['idMunicipio'=>286, 'nombre' => 'MIGUEL HIDALGO'],
['idMunicipio'=>287, 'nombre' => 'VENUSTIANO CARRANZA'],
['idMunicipio'=>271, 'nombre' => 'SIN INFORMACION'],
['idMunicipio'=>272, 'nombre' => 'SIN INFORMACION'],
['idMunicipio'=>273, 'nombre' => 'SIN INFORMACION'],
['idMunicipio'=>274, 'nombre' => 'SIN INFORMACION'],
['idMunicipio'=>275, 'nombre' => 'SIN INFORMACION'],
['idMunicipio'=>276, 'nombre' => 'SIN INFORMACION'],
['idMunicipio'=>277, 'nombre' => 'SIN INFORMACION'],
['idMunicipio'=>278, 'nombre' => 'SIN INFORMACION'],
['idMunicipio'=>279, 'nombre' => 'SIN INFORMACION'],
['idMunicipio'=>280, 'nombre' => 'SIN INFORMACION'],
['idMunicipio'=>281, 'nombre' => 'SIN INFORMACION'],
['idMunicipio'=>282, 'nombre' => 'SIN INFORMACION'],
['idMunicipio'=>283, 'nombre' => 'SIN INFORMACION'],
['idMunicipio'=>284, 'nombre' => 'SIN INFORMACION'],
['idMunicipio'=>285, 'nombre' => 'SIN INFORMACION'],
['idMunicipio'=>286, 'nombre' => 'SIN INFORMACION'],
['idMunicipio'=>2472, 'nombre' => 'SIN INFORMACION']

]);

    }
}
